spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://isteyft.top:3306/db_wallpaper
    url: jdbc:mysql://localhost:3306/db_wallpaper
    username: root
    password: 123
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 123@qq.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#PageHelper
pagehelper:
  helper-dialect: mysql # 数据库类型，默认mysql
  reasonable: true # 是否进行count查询
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数
  params: count=countSql # count查询SQL拼接方式
server:
  address: 0.0.0.0
  port: 8888
  ssl:
    enabled: true # 开启SSL支持
    key-store: classpath:ssl/isteyft.top.pfx # 或者是对应的jks文件，取决于您的实际证书格式
    key-store-password: 123 # 密钥库的密码
    keyStoreType: PKCS12 # 如果使用的是pfx文件，则通常是PKCS12，如果是jks则是JKS
    trust-store: classpath:ssl/isteyft.top.jks
    trust-store-password: 123 # 这里填写信任证书存储的密码
    trustStoreType: JKS